name: Build and push frontend

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push the Docker images
      uses: docker/build-push-action@v6
      with:
        registry: ghcr.io
        push: true
        tags: elisaado/allesbot:latest

