name: Build and push frontend

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: |
        docker build . -t allesbot
    - name: Push the Docker images
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: elisaado/allesbot:latest
